### ISSUE TITLE
Minor Code Enhancement

### ISSUE THREAD

**Issue by adityagiri3600** [sBubshait/desmos-drawer#1]
I'm not sure if what I'm doing rn is correct/allowed but I'm new to this and wondering if I can make a contribution to gain experience. I'm really impressed with this project. 

I have a small nitpicky "contribution" I can do. Hope you can show me the ropes! :)

**Comment by sBubshait** [comment]
Hey there!

Thank you for your interest in contributing! 🎉
I actually started this project for fun, but would really love to improve it further with your help.

It's absolutely okay to be new to this! Don't worry about whether it's correct or allowed – I'd really appreciate any and all contributions, big or small.

You mentioned that you have a small, nitpicky contribution in mind. Could you please elaborate on what you're thinking? Would love to hear more about it.

Once you're ready, you can create a pull request with your changes.

Looking forward to your contribution! 😊

Best,
Saleh.

**Comment by adityagiri3600** [comment]
Thank you so much for this! ☺️

I was thinking maybe I could make the if statement from line 41 in main.py a little shorter. I apologise if this is too nitpicky, but I hope you'll allow me to try it out.

also.. how do I create a pull request? can I contact you via discord or WhatsApp?

again thank you so much for being open and helping me get started!

-Aditya

**Comment by sBubshait** [comment]
Hey Aditya,

Yeah, please feel free to do so!
For privacy reasons, please just send me an email at Contact@Bubshait.me and I will give you my WhatsApp phone number there.

Thank you again for your interest!
